[proxy]
yourdomain ansible_user=ubuntu

[nodes]
db01.yourdomain ansible_user=ubuntu
db02.yourdomain ansible_user=ubuntu
app.yourdomain ansible_user=ubuntu
gitlab.yourdomain ansible_user=ubuntu
runner.yourdomain ansible_user=ubuntu
monitoring.yourdomain ansible_user=ubuntu
[nodes:vars]
ansible_ssh_common_args= '-o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -q ubuntu@yourdomain"'

[exporters]
yourdomain ansible_user=ubuntu
db01.yourdomain ansible_user=ubuntu
db02.yourdomain ansible_user=ubuntu
app.yourdomain ansible_user=ubuntu
gitlab.yourdomain ansible_user=ubuntu
runner.yourdomain ansible_user=ubuntu
[exporters:vars]
ansible_ssh_common_args= '-o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -q ubuntu@yourdomain"'
