---

- name: reenable node exporter service
  command: systemctl reenable exporter.service

- name: reinit node exporter
  command: initctl reload-configuration

- name: restart node exporter
  service:
    name: exporter
    state: restarted
