 mysql_port: 3306
 mysql_bind_address: "0.0.0.0"
 mysql_root_db_pass: wordpress

 mysql_user_name: wordpress
 mysql_user_pass: wordpress
 mysql_user_priv: "wordpress.*:ALL"
 mysql_remote_host: app.yourdomain

 mysql_db:
 - name: wordpress
 replicate: yes

 mysql_repl_user:
 - name: repl
   pass: wordpress

 binlog_do_db : wordpress
 mysql_repl_role: primary
 mysql_db_id: 7