- name: Install exporter on all instances except monitoring server
  hosts: exporters
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - exporter
  tags:
    - exporter
- name: Monitoring
  hosts: monitoring.yourdomain
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - monitoring
  tags:
    - monitoring
